/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/AH_Sco/H2O/AH_Sco-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/FX_Mon/H2O/FX_Mon-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS15060+0947/H2O/IRAS15060+0947-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/AH_Sco/H2O/AH_Sco-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/FX_Mon/H2O/FX_Mon-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS05345+3157/H2O/IRAS05345+3157-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS05554+2013/H2O/IRAS05554+2013-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS15060+0947/H2O/IRAS15060+0947-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/NML_Cyg/H2O/NML_Cyg-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/Orion_IRc2/H2O/Orion_IRc2-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/AH_Sco/H2O/AH_Sco-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/FX_Mon/H2O/FX_Mon-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS05345+3157/H2O/IRAS05345+3157-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS05554+2013/H2O/IRAS05554+2013-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS15060+0947/H2O/IRAS15060+0947-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/NML_Cyg/H2O/NML_Cyg-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/Orion_IRc2/H2O/Orion_IRc2-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/AH_Sco/H2O/AH_Sco-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/FX_Mon/H2O/FX_Mon-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS05345+3157/H2O/IRAS05345+3157-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS05554+2013/H2O/IRAS05554+2013-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS15060+0947/H2O/IRAS15060+0947-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/NML_Cyg/H2O/NML_Cyg-sort.plt
/usr/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/Orion_IRc2/H2O/Orion_IRc2-sort.plt
/usr/local/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/AH_Sco/H2O/AH_Sco-sort.plt
/usr/local/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/FX_Mon/H2O/FX_Mon-sort.plt
/usr/local/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS05345+3157/H2O/IRAS05345+3157-sort.plt
/usr/local/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS05554+2013/H2O/IRAS05554+2013-sort.plt
/usr/local/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/IRAS15060+0947/H2O/IRAS15060+0947-sort.plt
/usr/local/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/NML_Cyg/H2O/NML_Cyg-sort.plt
/usr/local/bin/perl /home/ryota/Desktop/OVO-AUTO/program/LCgnuplotH2O.pl /home/ryota/Desktop/OVO-AUTO/data/Orion_IRc2/H2O/Orion_IRc2-sort.plt
